[project]
name = "s4filter"
version = "1.0.0"
description = "utilities for sims4 modding"
readme = "README.md"
license = {text = "MIT"}
keywords = ["sims4", "mod", "modding", "utilities", "filter"]
requires-python = "==3.7.1"
classifiers = [
  "Programming Language :: Python"
]
dependencies = [
    "mypy==1.4.1",    # test
    "pytest==7.4.4",  # test
    "ruff==0.12.11",  # test
]

[project.urls]
Repository = "https://github.com/bsd-ac/s4filter"
License = "https://github.com/bsd-ac/s4filter/blob/main/LICENSE"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.mypy]
follow_imports = "silent"
ignore_missing_imports = true

[tool.setuptools.packages.find]
where = ["src"]
